alias: finance
author: Ling Hui
link: http://linghui.com
document: http://linghui/?t=35708
requirements:
    - crm
    - contactsCompany
    - supplier
    - bpm

auth_nodes:
    - finance.receivables.*
    - finance.payables.*
    - finance.financeAccount.*
    - finance.financeStreamline.get

include:
    js:
        - apps/finance/main
        - apps/finance/model
        - apps/finance/receivables
        - apps/finance/payables
        - apps/crm/model
        - apps/supplier/model
        - apps/contactsCompany/model
global_include:
    js:
        - apps/finance/plugin
navs:
    Finance:
        app: finance
        icon: money
        children:
            Streamline:
                app: finance
                children:
                    Accounts:
                        app: finance
                        link: finance/financeAccount
                    Receivables:
                        app: finance
                        link: finance/receivables
                    Payables:
                        app: finance
                        link: finance/payables
                    Finance Streamline:
                        app: finance
                        link: finance/financeStreamline
                    结算单:
                        app: finance
                        link: finance/statement