alias: messageCenter
author: Ling Hui
link: http://linghui.com

global_include:
    js:
        - apps/messageCenter/plugin
        - apps/messageCenter/service

main_include:
    js:
        - apps/messageCenter/plugin
        - apps/messageCenter/service