alias: myApp
author: 'zhanglei'
link: 
requirements: 
    - ship
    - bpm
    - crm
    - contactsCompany

auth_nodes:

load_modules:
    - ones.gridViewModule
    - ones.app.ship.model

include:
    js:
        - apps/myApp/plans
        - apps/myApp/main
        - apps/myApp/model
        - apps/ship/model
        - apps/storage/model
        - apps/contactsCompany/model
        - apps/crm/model

global_include:
    js:
        - apps/myApp/model

navs:
    Myapp1:
        children:
            Myapp2:
                app: myApp
                icon: sitemap
                children:
                    装运计划:
                        app: myApp
                        icon: users
                        link: myApp/plans
                    增加装运计划:
                        app: myApp
                        icon: users
                        link: myApp/plans/add/bill
            