alias: region
author: Ling Hui
link: http://linghui.com
requirements: 

auth_nodes:

include:
    js:
        - apps/region/main

global_include:
    js:
        - apps/region/model
        - apps/region/plugin
    css:
        - apps/region/static/style