alias: apptest
author: 
link: 
requirements: 

auth_nodes:

include:
    js:
        - apps/apptest/main
        - apps/apptest/model

navs:
    apptest1:
        children:
            apptest2:
                app: apptest
                icon: sitemap
                children:
                    apptest3:
                        app: apptest
                        icon: users
                        link: apptest/test